---
# Kustomize Feature List
# https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#kustomize-feature-list
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
namePrefix: production-
resources:
  - ../../base
  - namespace.yaml
patchesStrategicMerge:
  - deployment.yaml
